{-# LANGUAGE OverloadedStrings #-}
-- | Emit LLVM IR text from LIR.
--
-- All emission is pure — builds Text from LIR data structures.
-- The output is a complete .ll file that can be compiled with llc/clang++.
module Backends.LLVM.LIRToLLVM
  ( emitModule
  , addRuntimeExterns
  ) where

import Data.List (intercalate)
import Surface (Name)
import Backends.LLVM.LIR

-- | Emit a complete LLVM IR module as a String.
emitModule :: LModule -> String
emitModule m = unlines $
  [ "; Generated by tulam compiler (Phase A.1)"
  , "target triple = " ++ show targetTriple
  , ""
  , "; --- Runtime declarations ---"
  ] ++ map emitExtern (lmodExterns m)
    ++ [""]
    ++ concatMap emitGlobal (lmodGlobals m)
    ++ [""]
    ++ concatMap (\f -> emitFunction f ++ [""]) (lmodFuncs m)
  where
    -- Default target triple. Future: detect from host or make configurable.
    targetTriple = "arm64-apple-darwin" :: String

-- | Emit an extern function declaration.
emitExtern :: LFunction -> String
emitExtern f =
  "declare " ++ emitType (lfuncRetType f) ++ " @" ++ lfuncName f
  ++ "(" ++ intercalate ", " (map (emitType . snd) (lfuncParams f)) ++ ")"

-- | Emit a global constant.
emitGlobal :: LGlobal -> [String]
emitGlobal (LGlobalString name str) =
  let escaped = concatMap escapeChar str ++ "\\00"
      len = length str + 1  -- +1 for null terminator
  in ["@" ++ name ++ " = private unnamed_addr constant [" ++ show len ++ " x i8] c\"" ++ escaped ++ "\""]
emitGlobal (LGlobalInt name val ty) =
  ["@" ++ name ++ " = global " ++ emitType ty ++ " " ++ show val]

-- | Escape a character for LLVM IR string constants.
escapeChar :: Char -> String
escapeChar '\n' = "\\0A"
escapeChar '\r' = "\\0D"
escapeChar '\t' = "\\09"
escapeChar '\\' = "\\5C"
escapeChar '"'  = "\\22"
escapeChar '\0' = "\\00"
escapeChar c
  | fromEnum c < 32 || fromEnum c > 126 =
    let n = fromEnum c
    in "\\" ++ hexByte n
  | otherwise = [c]

hexByte :: Int -> String
hexByte n =
  let hi = n `div` 16
      lo = n `mod` 16
  in [hexDigit hi, hexDigit lo]

hexDigit :: Int -> Char
hexDigit d
  | d < 10    = toEnum (fromEnum '0' + d)
  | otherwise = toEnum (fromEnum 'A' + d - 10)

-- | Emit a function definition.
emitFunction :: LFunction -> [String]
emitFunction f =
  [ "define " ++ emitType (lfuncRetType f) ++ " @" ++ lfuncName f
    ++ "(" ++ intercalate ", " params ++ ") {"
  ] ++ concatMap emitBlock (lfuncBlocks f)
    ++ ["}"]
  where
    params = [ emitType ty ++ " %" ++ nm | (nm, ty) <- lfuncParams f ]

-- | Emit a basic block.
emitBlock :: LBlock -> [String]
emitBlock b =
  [lblockName b ++ ":"]
  ++ map emitNamedInstr (lblockInstrs b)
  ++ ["  " ++ emitTerminator (lblockTerm b)]

-- | Emit a named instruction.
emitNamedInstr :: (Name, LInstr) -> String
emitNamedInstr (name, instr)
  | instrResultType instr == LTVoid = "  " ++ emitInstr instr
  | otherwise = "  %" ++ name ++ " = " ++ emitInstr instr

-- | Emit an instruction.
emitInstr :: LInstr -> String
emitInstr (LAdd a b)     = emitBinOp "add" a b
emitInstr (LSub a b)     = emitBinOp "sub" a b
emitInstr (LMul a b)     = emitBinOp "mul" a b
emitInstr (LDiv a b)     = emitBinOp "sdiv" a b
emitInstr (LRem a b)     = emitBinOp "srem" a b
emitInstr (LUDiv a b)    = emitBinOp "udiv" a b
emitInstr (LURem a b)    = emitBinOp "urem" a b
emitInstr (LNeg a)       = emitBinOp "sub" (LLitInt 0 (operandType a)) a

emitInstr (LFAdd a b)    = emitBinOp "fadd" a b
emitInstr (LFSub a b)    = emitBinOp "fsub" a b
emitInstr (LFMul a b)    = emitBinOp "fmul" a b
emitInstr (LFDiv a b)    = emitBinOp "fdiv" a b
emitInstr (LFNeg a)      = "fneg " ++ emitType (operandType a) ++ " " ++ emitOperandBare a

emitInstr (LICmpEq a b)  = emitICmp "eq" a b
emitInstr (LICmpNe a b)  = emitICmp "ne" a b
emitInstr (LICmpLt a b)  = emitICmp "slt" a b
emitInstr (LICmpLe a b)  = emitICmp "sle" a b
emitInstr (LICmpGt a b)  = emitICmp "sgt" a b
emitInstr (LICmpGe a b)  = emitICmp "sge" a b
emitInstr (LICmpULt a b) = emitICmp "ult" a b
emitInstr (LICmpULe a b) = emitICmp "ule" a b
emitInstr (LICmpUGt a b) = emitICmp "ugt" a b
emitInstr (LICmpUGe a b) = emitICmp "uge" a b

emitInstr (LFCmpEq a b)  = emitFCmp "oeq" a b
emitInstr (LFCmpNe a b)  = emitFCmp "une" a b
emitInstr (LFCmpLt a b)  = emitFCmp "olt" a b
emitInstr (LFCmpLe a b)  = emitFCmp "ole" a b
emitInstr (LFCmpGt a b)  = emitFCmp "ogt" a b
emitInstr (LFCmpGe a b)  = emitFCmp "oge" a b

emitInstr (LAnd a b)      = emitBinOp "and" a b
emitInstr (LOr a b)       = emitBinOp "or" a b
emitInstr (LXor a b)      = emitBinOp "xor" a b
emitInstr (LShl a b)      = emitBinOp "shl" a b
emitInstr (LAShr a b)     = emitBinOp "ashr" a b
emitInstr (LLShr a b)     = emitBinOp "lshr" a b

emitInstr (LAlloc tag nf) =
  "call ptr @tlm_alloc(i32 " ++ show tag ++ ", i32 " ++ show nf ++ ")"
emitInstr (LStore val obj idx) =
  "call void @tlm_set_field(ptr " ++ emitOperandBare obj
  ++ ", i32 " ++ show idx
  ++ ", i64 " ++ emitOperandBare (coerceToI64 val) ++ ")"
emitInstr (LLoad obj idx ty) =
  -- Load raw i64, then bitcast/trunc as needed
  let loadCall = "call i64 @tlm_get_field(ptr " ++ emitOperandBare obj
                 ++ ", i32 " ++ show idx ++ ")"
  in if ty == LTInt64 || ty == LTWord64 || ty == LTPtr
     then loadCall  -- i64 is the native field type
     else loadCall  -- caller must add conversion instruction separately
emitInstr (LGetTag obj) =
  "call i16 @tlm_get_tag(ptr " ++ emitOperandBare obj ++ ")"

emitInstr (LCall fn args retTy) =
  "call " ++ emitType retTy ++ " @" ++ fn
  ++ "(" ++ intercalate ", " (map emitTypedOperand args) ++ ")"
emitInstr (LCallPtr fptr args retTy) =
  "call " ++ emitType retTy ++ " " ++ emitOperandBare fptr
  ++ "(" ++ intercalate ", " (map emitTypedOperand args) ++ ")"

emitInstr (LSext op ty)    = "sext " ++ emitTypedOperand op ++ " to " ++ emitType ty
emitInstr (LZext op ty)    = "zext " ++ emitTypedOperand op ++ " to " ++ emitType ty
emitInstr (LTrunc op ty)   = "trunc " ++ emitTypedOperand op ++ " to " ++ emitType ty
emitInstr (LSIToFP op ty)  = "sitofp " ++ emitTypedOperand op ++ " to " ++ emitType ty
emitInstr (LFPToSI op ty)  = "fptosi " ++ emitTypedOperand op ++ " to " ++ emitType ty
emitInstr (LFPExt op ty)   = "fpext " ++ emitTypedOperand op ++ " to " ++ emitType ty
emitInstr (LFPTrunc op ty) = "fptrunc " ++ emitTypedOperand op ++ " to " ++ emitType ty
emitInstr (LBitcast op ty) = "bitcast " ++ emitTypedOperand op ++ " to " ++ emitType ty
emitInstr (LIntToPtr op)   = "inttoptr " ++ emitTypedOperand op ++ " to ptr"
emitInstr (LPtrToInt op ty)= "ptrtoint " ++ emitTypedOperand op ++ " to " ++ emitType ty

emitInstr (LPhi pairs ty)  =
  "phi " ++ emitType ty ++ " "
  ++ intercalate ", " [ "[ " ++ emitOperandBare v ++ ", %" ++ lbl ++ " ]"
                       | (v, lbl) <- pairs ]
emitInstr (LCopy op) = emitInstr (LAdd op (LLitInt 0 (operandType op)))

-- | Helper: coerce an operand conceptually to i64 for field store.
-- In LLVM IR, the actual conversion happens at the instruction level.
coerceToI64 :: LOperand -> LOperand
coerceToI64 op = case operandType op of
  LTInt64  -> op
  LTWord64 -> op
  LTPtr    -> op   -- ptrtoint handled separately
  _        -> op   -- caller must handle narrower types

-- | Emit a binary operation.
emitBinOp :: String -> LOperand -> LOperand -> String
emitBinOp op a b =
  op ++ " " ++ emitType (operandType a) ++ " " ++ emitOperandBare a ++ ", " ++ emitOperandBare b

-- | Emit an integer comparison.
emitICmp :: String -> LOperand -> LOperand -> String
emitICmp cond a b =
  "icmp " ++ cond ++ " " ++ emitType (operandType a) ++ " " ++ emitOperandBare a ++ ", " ++ emitOperandBare b

-- | Emit a float comparison.
emitFCmp :: String -> LOperand -> LOperand -> String
emitFCmp cond a b =
  "fcmp " ++ cond ++ " " ++ emitType (operandType a) ++ " " ++ emitOperandBare a ++ ", " ++ emitOperandBare b

-- | Emit a block terminator.
emitTerminator :: LTerminator -> String
emitTerminator (LRet op) = "ret " ++ emitTypedOperand op
emitTerminator LRetVoid = "ret void"
emitTerminator (LBr lbl) = "br label %" ++ lbl
emitTerminator (LCondBr cond tLbl fLbl) =
  "br i1 " ++ emitOperandBare cond ++ ", label %" ++ tLbl ++ ", label %" ++ fLbl
emitTerminator (LSwitch val defLbl cases) =
  "switch " ++ emitTypedOperand val ++ ", label %" ++ defLbl ++ " [\n"
  ++ concatMap (\(n, lbl) -> "    " ++ emitType (operandType val) ++ " " ++ show n ++ ", label %" ++ lbl ++ "\n") cases
  ++ "  ]"
emitTerminator LUnreachable = "unreachable"

-- | Emit an LIR type as LLVM IR type string.
emitType :: LType -> String
emitType LTInt64     = "i64"
emitType LTInt32     = "i32"
emitType LTInt16     = "i16"
emitType LTInt8      = "i8"
emitType LTWord64    = "i64"   -- LLVM doesn't distinguish signed/unsigned in types
emitType LTWord32    = "i32"
emitType LTWord16    = "i16"
emitType LTWord8     = "i8"
emitType LTFloat64   = "double"
emitType LTFloat32   = "float"
emitType LTBool      = "i1"
emitType LTChar      = "i32"
emitType LTPtr       = "ptr"
emitType LTVoid      = "void"
emitType (LTFunPtr args ret) =
  emitType ret ++ " (" ++ intercalate ", " (map emitType args) ++ ")*"

-- | Emit a typed operand: "type value".
emitTypedOperand :: LOperand -> String
emitTypedOperand op = emitType (operandType op) ++ " " ++ emitOperandBare op

-- | Emit just the operand value (no type prefix).
emitOperandBare :: LOperand -> String
emitOperandBare (LVar name _)       = "%" ++ name
emitOperandBare (LLitInt n _)       = show n
emitOperandBare (LLitFloat d _)     = showLLVMDouble d
emitOperandBare (LLitBool True)     = "1"
emitOperandBare (LLitBool False)    = "0"
emitOperandBare LLitNull            = "null"
emitOperandBare (LLitString name str) =
  let len = length str + 1  -- +1 for null terminator
  in "getelementptr inbounds ([" ++ show len ++ " x i8], ptr @" ++ name ++ ", i64 0, i64 0)"

-- | Show a double in LLVM IR format (hex for exact representation).
showLLVMDouble :: Double -> String
showLLVMDouble d
  | isNaN d    = "0x7FF8000000000000"
  | isInfinite d && d > 0 = "0x7FF0000000000000"
  | isInfinite d = "0xFFF0000000000000"
  | d == 0.0    = "0.0"
  | otherwise    = show d  -- LLVM accepts decimal for simple cases

-- | Emit runtime function declarations needed by all modules.
runtimeExterns :: [LFunction]
runtimeExterns =
  [ extern "tlm_alloc"      [(""  , LTInt32), ("", LTInt32)] LTPtr
  , extern "tlm_get_field"  [("", LTPtr), ("", LTInt32)] LTInt64
  , extern "tlm_set_field"  [("", LTPtr), ("", LTInt32), ("", LTInt64)] LTVoid
  , extern "tlm_get_tag"    [("", LTPtr)] LTInt16
  , extern "tlm_print_int"  [("", LTInt64)] LTVoid
  , extern "tlm_print_float"[("", LTFloat64)] LTVoid
  , extern "tlm_print_string" [("", LTPtr)] LTVoid
  , extern "tlm_print_newline" [] LTVoid
  , extern "tlm_print_char" [("", LTInt32)] LTVoid
  , extern "tlm_print_bool" [("", LTInt32)] LTVoid
  , extern "tlm_error"      [("", LTPtr)] LTVoid
  , extern "tlm_rc_inc"     [("", LTPtr)] LTVoid
  , extern "tlm_rc_dec"     [("", LTPtr)] LTVoid
  ]
  where
    extern name params ret = LFunction name params ret [] True

-- | Get the standard runtime extern declarations.
getRuntimeExterns :: [LFunction]
getRuntimeExterns = runtimeExterns

-- | Helper to add runtime externs to a module, skipping any already declared.
addRuntimeExterns :: LModule -> LModule
addRuntimeExterns m = m { lmodExterns = lmodExterns m ++ newExterns }
  where
    existing = map lfuncName (lmodExterns m)
    newExterns = filter (\f -> lfuncName f `notElem` existing) getRuntimeExterns
